# Generated by Django 4.2.4 on 2023-08-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='aboutus',
        ),
    ]
