# Generated by Django 4.2.4 on 2023-08-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_rename_about_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_readmore_btn_text',
            field=models.CharField(default='Read More', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_readmore_btn_url',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
